openapi: 3.1.0
info:
  title: 06-jobsAPI
  version: 1.0.0
servers:
  - url: http://localhost:80/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      tags:
        - default
      summary: register user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: johny
                email: john@johny.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - default
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: deny@gmail.com
                password: aaaaaa
                name: '15'
                peer: 15
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs:
    post:
      tags:
        - default
      summary: create job
      requestBody:
        content: {}
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGY0NzgwN2RiMGQ1YzBhZjRmYzZiY2MiLCJuYW1lIjoiZWRvIiwiaWF0IjoxNjkzNzQzMTExLCJleHAiOjE2OTYzMzUxMTF9.UwAgNECrEXmylcLRneH3jXAR2hBGwNi2kBpl8-CDqv0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: get all jobs
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGY1YzI5MTI4ZjNlNzMyMDAyY2NmOTkiLCJuYW1lIjoiZGVueSIsImlhdCI6MTY5MzgyNzcyOSwiZXhwIjoxNjk2NDE5NzI5fQ.8vUctdkxzEm3xuearE0mvGwKrEssnE898LN2LkQVuK0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs/64f5d24d7e173e41549bd8df:
    get:
      tags:
        - default
      summary: get 1 job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: delete job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs/64f5d852ae562d45300eb178:
    patch:
      tags:
        - default
      summary: update job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: updated
                position: '1111'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}